### PR TITLE
Add the null check of get_script_url back

### PR DESCRIPTION
**Pull request by NavidZ**
The last change to this line removed the null check
of get_script_url. Adding it back and keeping the
regex functionality that was added in the previous change.

### CODE REVIEW

**Comment by NavidZ** [comment]
@annevk @jgraham 
We wanted to update the wpt for Chrome but the null check that was removed in the previous patch causes some issues in Chrome. Please have a look at this change and see if it looks okay.

**Comment by NavidZ** [comment]
@dtapuska

**Comment by dtapuska** [comment]
lgtm

**Comment by annevk** [comment]
Sorry about this and thanks for fixing!

**Pull request merged**
