### PR TITLE
Distinguish float/string types

### LINKED ISSUE #92: Check that returned ByteStrings/USVStrings are valid
All high bytes zero for ByteString and no unpaired surrogates for USVString.

### PR DESCRIPTION
**Pull request by gsnedders**
Fixes #92 and a bit more.

### CODE REVIEW

**Comment by gsnedders** [comment]
Hmm, this probably isn't that good. We probably want the `assert_equals(typeof value, "number");` first for all the number types. Because otherwise we can end up with it throwing (`fround` can throw through `ToNumber`).

**Comment by gsnedders** [comment]
@Ms2ger: r?

Previous comment was long ago addressed. In October.

**Comment by inexorabletash** [comment]
lgtm, fwiw

**Comment by jdm** [comment]
Agreed!

**Pull request merged**
