### PR TITLE
add checking of WorkerGlobalScope for DedicatedWorkerGlobalScope

### LINKED ISSUE #173: DedicatedWorkerGlobalScope type is named with WorkerGlobalScope in the Edge
Testharness.js support 3 web worker types when creating test environment (in the create_test_environment); Dedicated/Shared/ServerceWorkerGlobalScope.   Microsoft Edge support only DedicatedWorkerGlobalScope worker type , but with name of ‘WorkerGlobalScope’.   This different type name make create_test_enviroment throw exception when testharness.js is imported from the web worker scripts.

The proposal is to add extra check after ‘ServiceWorkerGlobalScope’ in the create_test_environment.

if ('WorkerGlobalScope' in self &&
   self instanceof WorkerGlobalScope) {
   return new DedicatedWorkerTestEnvironment();
}

### PR DESCRIPTION
**Pull request by cpsgchue**
Fixes #173. 

The change is just add 'WorkerGlobalScope' type name for creating DedicatedWorkerGlobalScope. 

It could be possible to add checking together in the line of 'DedicatedWorkerGlobalScope', but that could unnecessarily run for Shared/Service worker case that isn't desirable for supporting Edge only case.

### CODE REVIEW

**Comment by cpsgchue** [comment]
can someone review and merge this request?

**Comment by DigiTec** [comment]
I'm from the Microsoft Edge team and this is a change we had to make to our local testharness.js so that we could continue to run some regression suites against IE 11 as well. While Edge has fixed the issue we still regard IE 11 as a modern browser that testharness.js should support. 

We are in support of accepting this pull request.

**Comment by Ms2ger** [comment]
I s'pose.

**Comment by DigiTec** [comment]
Thank you!

**Pull request merged**
