### PR TITLE
Add assert_does_not_throw and its tests

### PR DESCRIPTION
**Pull request by calvaris**

### CODE REVIEW

**Comment by Ms2ger** [comment]
Why?

**Comment by calvaris** [comment]
There is a similar assertion in other test suites like tape for example. This would allow to make tests that can be more easily translated, for example.

We are using them in WebKit to translate the Streams API tests that are written with tape

**Comment by Ms2ger** [comment]
`test()` already catches exceptions, so `assert_does_not_throw(f)` is functionally equivalent to `f()`.

**Comment by zcorpan** [comment]
Yeah, I agree with @Ms2ger

**Pull request closed without merging**
