### PR TITLE
Run stringifier test in idlharness for attributes

### PR DESCRIPTION
**Pull request by zcorpan**
Ref. https://github.com/w3c/web-platform-tests/pull/3545

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/testharness.js/205)

### CODE REVIEW

**Comment by zcorpan** [comment]
@Ms2ger r?

**Comment by Ms2ger** [comment]
Move it behind the unforgeable check? I think `Location` might actually hit that.

**Comment by zcorpan** [comment]
Should this not run if it's [Unforgeable]? Does that also apply for `operation`?

**Comment by Ms2ger** [comment]
Maybe I'll think about it later.

**Pull request merged**
