### PR TITLE
Add environment scope to test name in case it is not Window

### PR DESCRIPTION
**Pull request by youennf**
Making a ''XXX' test name becoming [ Worker] XXX or [ ServiceWorker ] XXX

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/testharness.js/175)

### CODE REVIEW

**Comment by Ms2ger** [comment]
Not quite convinced here/

**Comment by youennf** [comment]
I think it might be of some use once uploading streams API whatwg tests.
@wanderview, @jgraham, any thoughts?

**Comment by youennf** [comment]
Related issue is https://github.com/w3c/testharness.js/issues/168

**Comment by youennf** [comment]
Streams API tests have been uploaded in web-platform-tests repository and illustrate the issue.

Running them on Chrome locally (http://localhost:8000/streams/count-queuing-strategy.https.html e.g.) shows that each test name is duplicated 3 times.
This gives a red warning when running them in a browser.
It is also not straightforward to identify which test result corresponds to which test flavor (window, worker, service worker).

We could update testharness to remove the ambiguity as proposed in the PR.
Or we could update streams tests to split test flavors in different test files, as dismissed in https://github.com/whatwg/streams/issues/411

@Ms2ger, wdyt?

**Comment by sideshowbarker** [comment]
@Ms2ger this one seems to be waiting on feedback from you

**Comment by Ms2ger** [comment]
Will defer to @jgraham. This might cause issues all non-Window test expectations to be invalidated...

Possibly using `.any.js` for those tests would be better.

**Comment by jgraham** [comment]
Yeah, invalidating all test names for non-window tests seems like a bad idea. That data can be regenerated but it isn't trivial to do and it seems like the streams tests could trivially solve this issue themselves.

I guess I should also make the stability bot reject PRs with duplicate test names.

**Pull request closed without merging**
