### PR TITLE
Set a test to ERROR if it has an unhandled promise rejections

### PR DESCRIPTION
**Pull request by gsnedders**
See http://www.w3.org/mid/556aa889-0ad1-9789-f1db-a148fe7a9929@nottheoilrig.com. 

@jablko, does this resolve that?

---

This change is [Reviewable](https://reviewable.io/reviews/w3c/testharness.js/219)

### CODE REVIEW

**Review by Ms2ger — APPROVED** [review]
LGTM

**Comment by jablko** [comment]
Looks good, but tests still pass even if one of their assertions fails, both when I run them with tools/runner and when I visit them directly, e.g. http://localhost:8000/fetch/api/cors/cors-redirect.html
I confirm that error_handler() is called, but not before notify_complete().
To see what I mean, change one of the assertions in fetch/api/cors/cors-redirect.js (for one) to assert_true(false). I expect the test to fail, but it passes.

**Comment by Ms2ger** [comment]
`fetch/api/cors/cors-redirect.html` is completely broken, I'm afraid. #220 makes it fail all of its subtests.

https://github.com/w3c/web-platform-tests/pull/4072 fixes the test, and exposes that Firefox fails half the subtests.

**Comment by jablko** [comment]
What about something like the following?

```diff
     };
 
     addEventListener("error", error_handler);
-    addEventListener("unhandledrejection", function(e){ error_handler(e.reason); });
+    addEventListener("unhandledrejection", function(e) {
+        error_handler(e.reason);
+        tests.notify_complete();
+    });
 
     test_environment.on_tests_ready();
 
```

@Ms2ger Thanks for fixing cors-redirect.html and promise_test()

**Comment by gsnedders** [comment]
@jgraham both me and @Ms2ger have decided to redirect the above question to you

**Comment by jgraham** [comment]
I don't think that an error caused by one test should prevent other tests from running, which that change would. If you wanted this to work better you would need to know which test was running at the time the error handler was called, which isn't really possible (and there might not be one).

**Comment by jablko** [comment]
@jgraham Would something like the following still prevent other tests from running?

```diff
     };
 
     addEventListener("error", error_handler);
-    addEventListener("unhandledrejection", function(e){ error_handler(e.reason); });
+    addEventListener("unhandledrejection", function(e) {
+        error_handler(e.reason);
+        if (tests.phase === tests.phases.COMPLETE) {
+            tests.notify_complete();
+        }
+    });
 
     test_environment.on_tests_ready();
 
```

**Comment by domenic** [comment]
It would be ideal if this didn't fail your test when there was a matching unhandledrejection/rejectionhandled pair. That would just mean that the rejection was handled later, which is legitimate.

**Comment by gsnedders** [comment]
@domenic can you throw together something for that? I can't say I know enough about the promises events to be confident I'm doing the right thing!

**Comment by jgraham** [comment]
If that isn't the common case you can `allow_uncaught_exceptions` just in the tests that need it. Obviously that means that you will also miss real exceptions though.

**Comment by jablko** [comment]
That makes sense. Can you point out a test where that might happen?

**Comment by domenic** [comment]
@gsnedders I gave this a try, but I wasn't able to figure out how to run code at the end of a test. Here is the code for tracking the rejections:

```js
    var rejections = new Map();
    addEventListener("unhandledrejection", function(e) {
        rejections.set(e.promise, e.reason);
    }, false);
    addEventListener("rejectionhandled", function(e) {
        rejections.delete(e.promise);
    });
```

Ideally at the end of each test we would check that `rejections.size === 0`, and if it's not, I guess error out with the first rejection?

**Comment by jgraham** [comment]
That seems non-deterministic since tests can run concurrently so you would assign the error to whichever test happened to end first. I guess you could make it set the overall harness status though.

**Comment by domenic** [comment]
Well, promise_tests cannot run concurrently, but I guess somebody could be using async_test, true. How do you set the overall harness status?

**Pull request merged**
