### PR TITLE
Support unions in idlharness

### PR DESCRIPTION
**Pull request by ayg**
Now with far less craziness.

---
This change is [Reviewable](https://reviewable.io/reviews/w3c/testharness.js/258)

### CODE REVIEW

**Comment by ayg** [comment]
(This fixes w3c/web-platform-tests#5034 and supersedes #257.)

**Comment by ayg** [comment]
@zcorpan Are you interested in reviewing?  It's a lot easier than the last one.  :)

**Comment by zcorpan** [comment]
With this change, 3 tests in html/dom/interfaces.html went from fail to pass:
```diff
< Fail	TrackEvent interface: new TrackEvent("addtrack", {track:document.createElement("track").track}) must inherit property "track" with the proper type (0)	Unrecognized type [object Object],[object Object],[object Object]
< Fail	CanvasRenderingContext2D interface: document.createElement("canvas").getContext("2d") must inherit property "strokeStyle" with the proper type (15)	Unrecognized type [object Object],[object Object],[object Object]
< Fail	CanvasRenderingContext2D interface: document.createElement("canvas").getContext("2d") must inherit property "fillStyle" with the proper type (16)	Unrecognized type [object Object],[object Object],[object Object]
```

If I change html/dom/resources/interfaces.idl as follows
```diff
@@ -1111,7 +1111,7 @@ interface CanvasImageSmoothing {
 [NoInterfaceObject]
 interface CanvasFillStrokeStyles {
   // colours and styles (see also the CanvasPathDrawingStyles and CanvasTextDrawingStyles interfaces)
-  attribute (DOMString or CanvasGradient or CanvasPattern) strokeStyle; // (default black)
+  attribute (boolean or long) strokeStyle; // (default black)
   attribute (DOMString or CanvasGradient or CanvasPattern) fillStyle; // (default black)
   CanvasGradient createLinearGradient(double x0, double y0, double x1, double y1);
   CanvasGradient createRadialGradient(double x0, double y0, double r0, double x1, double y1, double r1);
```
I get this failure:
> assert_true: Attribute has value "#000000" which doesn't match any of the types in the union expected true got false

and so this seems to work as intended!

The error message seems OK.

**Comment by zcorpan** [comment]
Thank you!

**Pull request merged**
