### PR TITLE
Specify useCapture argument in addEventListener calls

### PR DESCRIPTION
**Pull request by cvrebert**
For greater compatibility with very old browsers.

---

This change is [Reviewable](https://reviewable.io/reviews/w3c/testharness.js/215)

### CODE REVIEW

**Comment by domenic** [comment]
Why? What value is gained in supporting such browsers? Many tests, and probably testharness itself, already use features like Array.prototype.forEach and such that are beyond those browsers.

**Comment by cvrebert** [comment]
web-platform-tests can be useful for gathering historical compatibility data (e.g. https://github.com/Fyrd/caniuse/pull/2880), therefore it's nice to increase the compatibility of the test harness, so long as the changes are minor of course. I think everyone would agree that adding 1 hardcoded boolean parameter to 4 function calls is minor? If I was instead suggesting a major refactoring or adding 200LOC, then I would understand and share your concern.

> Many tests, and probably testharness itself, already use features like Array.prototype.forEach and such that are beyond those browsers.

[`forEach` was added way back in Firefox 1.5](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Browser_compatibility).
I know, amazing, right? 😄 

In my specific case, the harness broke in Firefox 4, but solely on account of this `addEventListener` `useCapture` requiredness difference. After manually patching in the `, false`s,  http://w3c-test.org/dom/nodes/Node-contains.html passes with flying colors in Firefox 4.

**Comment by Ms2ger** [comment]
I don't see a reason not to do this. Do also fix the `removeEventListener` call, though.

**Comment by sideshowbarker** [comment]
> I don't see a reason not to do this. Do also fix the `removeEventListener` call, though.

@cvrebert if you’re still interested in seeing this get merged

**Comment by gsnedders** [comment]
@domenic I've definitely run tests in old browsers to try and work out when the behaviour dates from.  I don't think we should require every test be runnable in old browsers—but having the actual test harness work is a good thing, IMO, because it makes it possible.

**Comment by Ms2ger** [comment]
Thanks! Unfortunately, it looks like there's conflicts you need to resolve.

**Comment by cvrebert** [comment]
Thanks for the courtesy rebase, Michael.

**Comment by sideshowbarker** [comment]
> Thanks for the courtesy rebase, Michael.

cheers

**Pull request merged**
